# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "D:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = F:\Programming\jyx-program\C++\DuckShell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = F:\Programming\jyx-program\C++\DuckShell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"D:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"D:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start F:\Programming\jyx-program\C++\DuckShell\CMakeFiles F:\Programming\jyx-program\C++\DuckShell\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start F:\Programming\jyx-program\C++\DuckShell\CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start F:\Programming\jyx-program\C++\DuckShell\CMakeFiles F:\Programming\jyx-program\C++\DuckShell\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start F:\Programming\jyx-program\C++\DuckShell\CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DuckShell

# Build rule for target.
DuckShell: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 DuckShell
.PHONY : DuckShell

# fast build rule for target.
DuckShell/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\DuckShell.dir\build.make CMakeFiles/DuckShell.dir/build
.PHONY : DuckShell/fast

src/global_vars.obj: src/global_vars.cpp.obj
.PHONY : src/global_vars.obj

# target to build an object file
src/global_vars.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\DuckShell.dir\build.make CMakeFiles/DuckShell.dir/src/global_vars.cpp.obj
.PHONY : src/global_vars.cpp.obj

src/global_vars.i: src/global_vars.cpp.i
.PHONY : src/global_vars.i

# target to preprocess a source file
src/global_vars.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\DuckShell.dir\build.make CMakeFiles/DuckShell.dir/src/global_vars.cpp.i
.PHONY : src/global_vars.cpp.i

src/global_vars.s: src/global_vars.cpp.s
.PHONY : src/global_vars.s

# target to generate assembly for a file
src/global_vars.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\DuckShell.dir\build.make CMakeFiles/DuckShell.dir/src/global_vars.cpp.s
.PHONY : src/global_vars.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\DuckShell.dir\build.make CMakeFiles/DuckShell.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\DuckShell.dir\build.make CMakeFiles/DuckShell.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\DuckShell.dir\build.make CMakeFiles/DuckShell.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/plugins/plugins_manager.obj: src/plugins/plugins_manager.cpp.obj
.PHONY : src/plugins/plugins_manager.obj

# target to build an object file
src/plugins/plugins_manager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\DuckShell.dir\build.make CMakeFiles/DuckShell.dir/src/plugins/plugins_manager.cpp.obj
.PHONY : src/plugins/plugins_manager.cpp.obj

src/plugins/plugins_manager.i: src/plugins/plugins_manager.cpp.i
.PHONY : src/plugins/plugins_manager.i

# target to preprocess a source file
src/plugins/plugins_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\DuckShell.dir\build.make CMakeFiles/DuckShell.dir/src/plugins/plugins_manager.cpp.i
.PHONY : src/plugins/plugins_manager.cpp.i

src/plugins/plugins_manager.s: src/plugins/plugins_manager.cpp.s
.PHONY : src/plugins/plugins_manager.s

# target to generate assembly for a file
src/plugins/plugins_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\DuckShell.dir\build.make CMakeFiles/DuckShell.dir/src/plugins/plugins_manager.cpp.s
.PHONY : src/plugins/plugins_manager.cpp.s

src/shell/main_shell.obj: src/shell/main_shell.cpp.obj
.PHONY : src/shell/main_shell.obj

# target to build an object file
src/shell/main_shell.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\DuckShell.dir\build.make CMakeFiles/DuckShell.dir/src/shell/main_shell.cpp.obj
.PHONY : src/shell/main_shell.cpp.obj

src/shell/main_shell.i: src/shell/main_shell.cpp.i
.PHONY : src/shell/main_shell.i

# target to preprocess a source file
src/shell/main_shell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\DuckShell.dir\build.make CMakeFiles/DuckShell.dir/src/shell/main_shell.cpp.i
.PHONY : src/shell/main_shell.cpp.i

src/shell/main_shell.s: src/shell/main_shell.cpp.s
.PHONY : src/shell/main_shell.s

# target to generate assembly for a file
src/shell/main_shell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\DuckShell.dir\build.make CMakeFiles/DuckShell.dir/src/shell/main_shell.cpp.s
.PHONY : src/shell/main_shell.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... codegen
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... DuckShell
	@echo ... src/global_vars.obj
	@echo ... src/global_vars.i
	@echo ... src/global_vars.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/plugins/plugins_manager.obj
	@echo ... src/plugins/plugins_manager.i
	@echo ... src/plugins/plugins_manager.s
	@echo ... src/shell/main_shell.obj
	@echo ... src/shell/main_shell.i
	@echo ... src/shell/main_shell.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

